### PR TITLE
fix(commands): sPopCount return Array<string>

### LINKED ISSUE #3004: [v5]spop and sPopCount types are incorrect
### Description

Hi, I think the type returned by functions `spop` and `spopCount` are invalid. Actually the type return : 

```
Promise<string | null>
```

But this functions return an array of string. The return type should be `Promise<string[]>` instead.

### Node.js Version

22.16.0

### Redis Server Version

_No response_

### Node Redis Version

5.5.6

### Platform

macOS

### Logs

```bash

```

### PR DESCRIPTION
**Pull request by nkaradzhov**
fix sPopCount return type - should be an array instead of string | null

Also, touch the tests for sPop and sPopCount to use the new parseCommand API

fixes #3004

### Checklist

- [x] Does `npm test` pass with this change (including linting)?
- [x] Is the new or changed code fully tested?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?

### CODE REVIEW

File: packages/client/lib/commands/SPOP_COUNT.ts [hunk 1]
```diff
@@ -16,5 +16,5 @@ export default {
     parser.pushKey(key);
     parser.push(count.toString());
   },
-  transformReply: undefined as unknown as () => BlobStringReply | NullReply
+  transformReply: undefined as unknown as () => ArrayReply<string>
```
Comment (htemelski-oss) [inline packages/client/lib/commands/SPOP_COUNT.ts:19]: Isn't the proper return type `ArrayReply<string> | NullReply` ?
Based on the [docs](https://redis.io/docs/latest/commands/spop/) we can get Nil/Null if the key doesn't exist

Comment (bobymicroby) [reply packages/client/lib/commands/SPOP_COUNT.ts:19]: according to docs ( with count  parameter ) :

One of the following:
[Nil reply](https://redis.io/docs/latest/develop/reference/protocol-spec#bulk-strings): if the key does not exist.
[Array reply](https://redis.io/docs/latest/develop/reference/protocol-spec#arrays): when called with the count argument, a list of the removed members.

I agree with Hristo  about the return type : `ArrayReply<string> | NullReply`

Comment (nkaradzhov) [reply packages/client/lib/commands/SPOP_COUNT.ts:19]: resolved offline, if count is provided, the server always returns an array
